export type PrivateEnvVariableName = keyof typeof privateEnvVariableName

export const privateEnvVariableName = {
  ENV_NAME: "ENV_NAME",

  TOKEN_SECRET: "TOKEN_SECRET",

  B2_KEY_ID: "B2_KEY_ID",
  B2_KEY: "B2_KEY",
  B2_BUCKET_ID: "B2_BUCKET_ID",
  B2_BUCKET_NAME: "B2_BUCKET_NAME",
  B2_BUCKET_PUBLIC_BASE_URL: "B2_BUCKET_PUBLIC_BASE_URL",

  VERSION: "VERSION",

  HEADER_CACHE_CONTROL: "HEADER_CACHE_CONTROL",
  HEADER_CORS_ALLOW_ORIGIN: "HEADER_CORS_ALLOW_ORIGIN",
  HEADER_CORS_MAX_AGE: "HEADER_CORS_MAX_AGE",

  KV: "KV",
} as const
